server:
  port: 8081
  servlet:
    context-path: /crud

spring:
  application:
    name: crud
  
  data:
    mongodb:
      uri: mongodb://root:root@srv-mongo/registros
  datasource:
    driverClassName: mongodb.jdbc.MongoDriver
    url: jdbc:mongodb://root:root@srv-mongo:21017/registros
    username: root
    password: root     
 
eureka:
  instance: 
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka
   